#!/usr/bin/env bash

# exit when a command fails.
set -o errexit
# exit when your script tries to use undeclared variables.
set -o nounset
# The exit status of the last command that threw a non-zero exit code is returned.
set -o pipefail

HOOKS_DIR=$(git config core.hooksPath)
if [ -z "${HOOKS_DIR}" ]; then
    HOOKS_DIR=$(dirname $0)
fi

LIBS_DIR=${LIBS_DIR:-$(dirname $0)/libs}

PROJECT_DIR=$(pwd)

source ${LIBS_DIR}/base_hook.sh "pre-commit" 




